name: fitatu_barcode_scanner
sdkPath: .fvm/flutter_sdk

packages:
  - .
  - example

command:
  bootstrap:
    usePubspecOverrides: true
    environment:
      sdk: ">=3.10.4 <4.0.0"
      flutter: ">=3.38.5"
