name: fitatu_barcode_scanner_example
description: Demonstrates how to use the fitatu_barcode_scanner plugin.
publish_to: 'none'

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.35.5"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  fitatu_barcode_scanner:
    path: ./

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

